# Project information
site_name: BitDocs
site_url: https://docs.1bitlog.ru/
site_author: Thorgathis, 1BitLog

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Repository
repo_name: IBit-mc-server/BitDocs
repo_url: https://github.com/IBit-mc-server/BitDocs

theme:
  name: material
  language: ru
  
  icon:
    repo: fontawesome/brands/github
  logo: icon.png
  favicon: images/favicon.png
  
  extra:
    homepage: https://docs.1bitlog.ru/
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
plugins:
  - table-reader
# Page tree
nav:
  - Главная: index.md
  - Как играть?:
    - О нас: guides/about.md
    - Добыча монет: guides/mining.md
    - Список монет: guides/cripto.md
    - Компьютер: guides/equipment.md
    - Смартфон: guides/phone.md
    - Терминалы: guides/terminals.md
  - Это полезно знать:
    - Аукционы: base/auctions.md
    - Телепорты к игрокам: base/teleports.md
    - Точки дома: base/homes.md
    - Приваты и регионы: base/regions.md
    - Варпы и спавны: base/warps.md
    - Онлайн карта: base/maps.md


