site_name: My Docs

theme:
  name: material
  language: ru
  
  features:
    - navigation.tabs
    - navigation.instant
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
