# Project information
site_name: BitDocs
site_url: https://ibit-mc-server.github.io/BitDocs/
site_author: Thorgathis, 1BitLog

# Repository
repo_name: IBit-mc-server/BitDocs
repo_url: https://github.com/IBit-mc-server/BitDocs

theme:
  name: material
  language: ru
  
  logo: images/logo.png
  favicon: images/favicon.png
  
  extra:
    homepage: https://ibit-mc-server.github.io/BitDocs/
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Page tree
nav:
  - Home: index.md
  - Guides:
    - О нас: guides/about.md
    - Creating your site: creating-your-site.md
    - Publishing your site: publishing-your-site.md
    - Customization: customization.md
    - Browser support: browser-support.md
    - Philosophy: philosophy.md
    - Alternatives: alternatives.md
